products:
  groww:
    display_name: Groww
    google_play_package: com.nextbillion.groww
    google_doc:
      title: "Weekly Review Pulse — Groww"
      document_id: 1_xAZm0QIsGGrd06sthovoSKMez9DnLm5Xiw_BZ3-n4U
    stakeholders:
      to:
        - barath9677081188@gmail.com
        - barathsrinivasan@outlook.com  
      cc: []